name: Lint and Prettier

on:
  push:
    branches-ignore:
      - main  # Ignore the main branch to prevent duplicate runs
  pull_request:
    branches:
      - '*'  # Run on all branches for pull requests

jobs:
  lint-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run prettier
